### ISSUE TITLE
Source not updated: OxygenOS OpenBeta 1/2

### ISSUE THREAD

**Issue by ghost** [OnePlusOSS/android_kernel_oneplus_sm7250#1]
Hi Oneplus,

It seems that the source code available in this repository is not updated with the latest version of OxygenOS Open Beta 1 publicly distributed for Oneplus Nord.

I therefore ask you to release all the kernel source code related to the OxygenOS OpenBeta 1 as quickly as possible in compliance with the GPL v2 license terms.

Thanks

**Comment by ghost** [comment]
Oneplus has released Open Beta 2 but has not updated the kernel sources yet, this is not acceptable.

You must update the kernel sources as quickly as possible

**Comment by filjusz** [comment]
Is it ok now?

**Comment by ghost** [comment]
It looks good to me, I close this
