### ISSUE TITLE
So? It's 125 and you say it's 113? Or are you dumb?

### ISSUE THREAD

**Issue by KakatkarAkshay** [OnePlusOSS/android_kernel_oneplus_sm7250#2]
https://github.com/OnePlusOSS/android_kernel_oneplus_sm7250/commit/398ebcda444780f201948031c0843b42ac8c3b25#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L4
All the upstream changes are still there then why the f are you saying it's 113? Who gave you your jobs?

**Comment by KakatkarAkshay** [comment]
@Agarwal-Harshit

**Comment by synt4x93** [comment]
Impressive, haven't seen commit rape like this for a long time.

**Comment by danascape** [comment]
New interns

**Comment by KakatkarAkshay** [comment]
> New interns

Interns doing production kernel, nice company

**Comment by Manish4586** [comment]
Pro god's

**Comment by synt4x93** [comment]
Guess they haven't heard of code review

**Comment by maade93791** [comment]
cool

**Comment by ZIDAN44** [comment]
lmao

**Comment by tattwamashi** [comment]
This is the proness we needed... Proness at its simplified stage ...

**Comment by renoxtv** [comment]
and i was going to buy a oneplus at some point... 😆

**Comment by elginsk8r** [comment]
They probably didn't even compile the kernel and test to verify they uploaded the right sources. OP is going to shit now that Carl Pei is no longer with the company.

**Comment by tattwamashi** [comment]
> They probably didn't even compile the kernel and test to verify they uploaded the right sources. OP is going to shit now that Carl Pei is no longer with the company.

OP wants to takedown Xiaomi tho🤣

**Comment by synt4x93** [comment]
> > They probably didn't even compile the kernel and test to verify they uploaded the right sources. OP is going to shit now that Carl Pei is no longer with the company.
> 
> OP wants to takedown Xiaomi tho

We can only dream

**Comment by KakatkarAkshay** [comment]
Seems fine in newer source now
