### ISSUE TITLE
Where is Nord CE Kernel Source?

### ISSUE THREAD

**Issue by KakatkarAkshay** [OnePlusOSS/android_kernel_oneplus_sm7250#5]
OnePlus Nord CE was released on 10 June 2021. 
Today is 24 July 2021 which means it has been 1 month and 14 days.
Still there is no kernel source for Nord CE. Which is a violation of Linux Kernel GPL.

**Comment by Subinsmani** [comment]
Very sad 🥲

**Comment by manugame** [comment]
Please release the Nord CE Kernel Source

**Comment by lzgmc** [comment]
Looks like they finally released the Nord CE source here https://github.com/OnePlusOSS/android_kernel_oneplus_sm7225 and here https://github.com/OnePlusOSS/android_vendor_qcom_opensource_audio_kernel_sm7225
